AllCops:
  TargetRubyVersion: 3.1.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'spec/**/*'
    - 'Gemfile'
    - 'config.ru'
    - 'Rakefile'
    - 'prefix_api_key.gemspec'

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false
