name: RuboCop

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Install dependencies
      run: |
        gem install bundler
        gem install rubocop
        bundle install --jobs 4 --retry 3

    - name: Run RuboCop
      run: bundle exec rubocop
